configs:
  runs:
    - protocol_name: "ngap"
      output_dir: ./output"
      actor: "ng-ran node"
      actors:
        - actor: "ng-ran node"
          as: "source"
        - actor: "amf"
          as: "target"
      publishers:
        - name: "SctpProxy"
          ref: 1
          actors:
            - "source"
            - "target"
      agents:
        - name: "NetworkFunctionProxy"
          configs:
            ip: "192.168.56.101"
            port: 9000
          options:
            compose_yaml_path: "./free5gc-compose/docker-compose.yaml"
            network_name: "privnet"
            certs_path: "./free5gc-compose/cert"
            proxy_port: 8080
            restart_on_epoch: true
            restart_on_fault: true
            exclude:
              - "mongodb"
              - "webui"
        - name: "ComposeRestart"
          configs:
            ip: "192.168.56.101"
            port: 9001
          options:
            compose_yaml_path: "./free5gc-compose/docker-compose.yaml"
            restart_on_epoch: true
            restart_on_fault: true
            clean_volumes_on_restart: true
        - name: "ContainerMonitor"
          configs:
            ip: "192.168.56.101"
            port: 9002
          options:
            containers:
              - "upf"
              - "nrf"
              - "amf"
              - "ausf"
              - "nssf"
              - "pcf"
              - "smf"
              - "udm"
              - "udr"
              - "chf"
              - "n3iwf"
              - "nef"
        - name: "NetworkSniffer"
          configs:
            ip: "127.0.0.1"
            port: 9003
          options:
            iface: "enp0s8"
            filter: "sctp"
            restart_on_epoch: true
            restart_on_fault: true
        - name: "CommandExec"
          configs:
            ip: "192.168.56.101"
            port: 9004
          options:
            cmd: "./scripts/health_check.py ./free5gc-compose/docker-compose.yaml"
            exec_on_test_start: true
            max_executions: 1
            reset_on_epoch_end: true
            reset_on_fault: true
        - name: "CommandExec"
          configs:
            ip: "192.168.56.101"
            port: 9005
          options:
            cmd: "./scripts/register_sim.py 127.0.0.1:5000 admin free5gc 208930000000001 8baf473f2f8fd09487cccbd7097c6862 OPc 8e27b6af0e692e750f32667a3b14605d"
            exec_on_test_start: true
            max_executions: 1
            reset_on_epoch_end: true
            reset_on_fault: true
        - name: "NetworkProxy"
          id: 1
          configs:
            ip: "127.0.0.1"
            port: 9006
          options:
            listen:
              ip: "127.0.0.1"
              port: 38412
            forward:
              from_ip: "192.168.56.102"
              to_ip: "192.168.56.101"
              to_port: 38412
            restart_on_test: true
        - name: "UERANSIMController"
          configs:
            ip: "127.0.0.1"
            port: 9007
          options:
            gnb:
              exe_path: "./UERANSIM/build/nr-gnb"
              config_path: "./UERANSIM/config/gnb_w_proxy.yaml"
              direct_config_path: "./UERANSIM/config/gnb.yaml"
            ue:
              exe_path: "./UERANSIM/build/nr-ue"
              config_path: "./UERANSIM/config/ue.yaml"
            cli_path: "./UERANSIM/build/nr-cli"

    - protocol_name: "nas-mm"
      output_dir: "./output"
      actor: "ue"
      actors:
        - actor: "ue"
          as: "source"
        - actor: "amf"
          as: "target"
      publishers:
        - name: "NetworkProxy"
          ref: 1
          actors:
            - "source"
            - "target"
      agents:
        - name: "NetworkFunctionProxy"
          configs:
            ip: "192.168.56.101"
            port: 9000
          options:
            compose_yaml_path: "./free5gc-compose/docker-compose.yaml"
            network_name: "privnet"
            certs_path: "./free5gc-compose/cert"
            proxy_port: 8080
            restart_on_test: true
            exclude:
              - "mongodb"
              - "webui"
        - name: "ComposeRestart"
          configs:
            ip: "192.168.56.101"
            port: 9001
          options:
            compose_yaml_path: "./free5gc-compose/docker-compose.yaml"
            restart_on_test: true
            clean_volumes_on_restart: true
        - name: "ContainerMonitor"
          configs:
            ip: "192.168.56.101"
            port: 9002
          options:
            containers:
              - "upf"
              - "nrf"
              - "amf"
              - "ausf"
              - "nssf"
              - "pcf"
              - "smf"
              - "udm"
              - "udr"
              - "chf"
              - "n3iwf"
              - "nef"
        - name: "NetworkSniffer"
          configs:
            ip: "127.0.0.1"
            port: 9003
          options:
            iface: "enp0s8"
            filter: "sctp"
            restart_on_test: true
        - name: "CommandExec"
          configs:
            ip: "192.168.56.101"
            port: 9004
          options:
            cmd: "./scripts/health_check.py ./free5gc-compose/docker-compose.yaml"
            exec_on_test_start: true
        - name: "CommandExec"
          configs:
            ip: "192.168.56.101"
            port: 9005
          options:
            cmd: "./scripts/register_sim.py 127.0.0.1:5000 admin free5gc 208930000000001 8baf473f2f8fd09487cccbd7097c6862 OPc 8e27b6af0e692e750f32667a3b14605d"
            exec_on_test_start: true
        - name: "NetworkProxy"
          id: 1
          configs:
            ip: "127.0.0.1"
            port: 9006
          options:
            listen:
              ip: "127.0.0.1"
              port: 38412
            forward:
              from_ip: "192.168.56.102"
              to_ip: "192.168.56.101"
              to_port: 38412
            restart_on_test: true
        - name: "UERANSIMController"
          configs:
            ip: "127.0.0.1"
            port: 9007
          options:
            gnb:
              exe_path: "./UERANSIM/build/nr-gnb"
              config_path: "./UERANSIM/config/gnb_w_proxy.yaml"
              direct_config_path: "./UERANSIM/config/gnb.yaml"
            ue:
              exe_path: "./UERANSIM/build/nr-ue"
              config_path: "./UERANSIM/config/ue.yaml"
            cli_path: "./UERANSIM/build/nr-cli"
      encoders:
        - name: "NASSecurity"
          id: 2
          configs:
            op: "8e27b6af0e692e750f32667a3b14605d"
            op_type: "OPC"
            key: "8baf473f2f8fd09487cccbd7097c6862"
            mcc: 208
            mnc: 93
            supi: "208930000000001"
      decoders:
        - name: "NASSecurity"
          ref: 2

    - protocol_name: "nas-sm"
      output_dir: "./output"
      actor: "ue"
      actors:
        - actor: "ue"
          as: "source"
        - actor: "smf"
          as: "target"
      publishers:
        - name: "NetworkProxy"
          ref: 1
          actors:
            - "source"
            - "target"
      agents:
        - name: "NetworkFunctionProxy"
          configs:
            ip: "192.168.56.101"
            port: 9000
          options:
            compose_yaml_path: "./free5gc-compose/docker-compose.yaml"
            network_name: "privnet"
            certs_path: "./free5gc-compose/cert"
            proxy_port: 8080
            restart_on_epoch: true
            restart_on_fault: true
            exclude:
              - "mongodb"
              - "webui"
        - name: "ComposeRestart"
          configs:
            ip: "192.168.56.101"
            port: 9001
          options:
            compose_yaml_path: "./free5gc-compose/docker-compose.yaml"
            restart_on_epoch: true
            restart_on_fault: true
            clean_volumes_on_restart: true
        - name: "ContainerMonitor"
          configs:
            ip: "192.168.56.101"
            port: 9002
          options:
            containers:
              - "upf"
              - "nrf"
              - "amf"
              - "ausf"
              - "nssf"
              - "pcf"
              - "smf"
              - "udm"
              - "udr"
              - "chf"
              - "n3iwf"
              - "nef"
        - name: "NetworkSniffer"
          configs:
            ip: "127.0.0.1"
            port: 9003
          options:
            iface: "enp0s8"
            filter: "sctp"
            restart_on_epoch: true
            restart_on_fault: true
        - name: "CommandExec"
          configs:
            ip: "192.168.56.101"
            port: 9004
          options:
            cmd: "./scripts/health_check.py ./free5gc-compose/docker-compose.yaml"
            exec_on_test_start: true
            max_executions: 1
            reset_on_epoch_end: true
            reset_on_fault: true
        - name: "CommandExec"
          configs:
            ip: "192.168.56.101"
            port: 9005
          options:
            cmd: "./scripts/register_sim.py 127.0.0.1:5000 admin free5gc 208930000000001 8baf473f2f8fd09487cccbd7097c6862 OPc 8e27b6af0e692e750f32667a3b14605d"
            exec_on_test_start: true
            max_executions: 1
            reset_on_epoch_end: true
            reset_on_fault: true
        - name: "NetworkProxy"
          id: 1
          configs:
            ip: "127.0.0.1"
            port: 9006
          options:
            listen:
              ip: "127.0.0.1"
              port: 38412
            forward:
              from_ip: "192.168.56.102"
              to_ip: "192.168.56.101"
              to_port: 38412
            sim:
              op: "8e27b6af0e692e750f32667a3b14605d"
              op_type: "OPC"
              key: "8baf473f2f8fd09487cccbd7097c6862"
              mcc: 208
              mnc: 93
              supi: "208930000000001"
            restart_on_test: true
        - name: "UERANSIMController"
          configs:
            ip: "127.0.0.1"
            port: 9007
          options:
            gnb:
              exe_path: "./UERANSIM/build/nr-gnb"
              config_path: "./UERANSIM/config/gnb_w_proxy.yaml"
              direct_config_path: "./UERANSIM/config/gnb.yaml"
            ue:
              exe_path: "./UERANSIM/build/nr-ue"
              config_path: "./UERANSIM/config/ue.yaml"
            cli_path: "./UERANSIM/build/nr-cli"
