name: Build docs

# Build the documentation whenever there are new tagged commits on main
on:
  push:
    branches:
      - main
    tags:
      - "*"

# Restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13-dev"

      - name: Install other dependencies
        run: sudo apt-get update && sudo apt-get install -y make libsctp-dev

      - name: Create venv
        run: python3 -m venv .venv

      - name: Activate venv
        run: |
          # this is the same as doing: source .venv/bin/activate
          export VIRTUAL_ENV="$(pwd)/.venv"
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" > "$GITHUB_ENV"
          echo "$VIRTUAL_ENV/bin" >> "$GITHUB_PATH"

      - name: Install Poetry
        run: pip install poetry

      - name: Build the documentation
        run: make docs

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # Note: This requires a free repo
  #
  # Deploy the artifact to GitHub pages.
  #deploy:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  permissions:
  #    pages: write
  #    id-token: write
  #  environment:
  #    name: github-pages
  #    url: ${{ steps.deployment.outputs.page_url }}
  #  steps:
  #    - id: deployment
  #      uses: actions/deploy-pages@v4
